### ISSUE TITLE
Outdated schematics

### ISSUE THREAD

**Issue by ThomasCZ** [BPI-STEAM/BPI-Leaf-S3-Doc#6]
Could you please update board schematics?

**Comment by Wind-stormger** [comment]
8388365df9f17bc836f5e9dcfa3316a3da1277cf

**Comment by astrolemonade** [comment]
@Wind-stormger sorry to bother you! Can you add a hardware revision history? I am trying to understand what changed between 0.1 and 1.0 and between 1.0 and 1.1.
